spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cardealership
    username: cardealership
    password: cardealership
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080